set_property PACKAGE_PIN AC14 	[get_ports {ADC_PORT_ad7606_os[0]}]
set_property PACKAGE_PIN AC13 	[get_ports {ADC_PORT_ad7606_os[1]}]
set_property PACKAGE_PIN AC12 	[get_ports {ADC_PORT_ad7606_os[2]}]
set_property PACKAGE_PIN AB12 	[get_ports ADC_PORT_ad7606_convstab]
set_property PACKAGE_PIN AF12 	[get_ports ADC_PORT_ad7606_reset]
set_property PACKAGE_PIN AE12 	[get_ports ADC_PORT_ad7606_rd]
set_property PACKAGE_PIN AD14 	[get_ports ADC_PORT_ad7606_cs]
set_property PACKAGE_PIN AD13 	[get_ports ADC_PORT_ad7606_busy]
set_property PACKAGE_PIN AH12 	[get_ports ADC_PORT_ad7606_first_data]
set_property PACKAGE_PIN AH13  [get_ports {ADC_PORT_ad7606_data[0]}]
set_property PACKAGE_PIN AH14  [get_ports {ADC_PORT_ad7606_data[1]}]
set_property PACKAGE_PIN AJ13  [get_ports {ADC_PORT_ad7606_data[2]}]
set_property PACKAGE_PIN AJ14  [get_ports {ADC_PORT_ad7606_data[3]}]
set_property PACKAGE_PIN AK12	  [get_ports {ADC_PORT_ad7606_data[4]}]
set_property PACKAGE_PIN AK13  [get_ports {ADC_PORT_ad7606_data[5]}]
set_property PACKAGE_PIN AB14  [get_ports {ADC_PORT_ad7606_data[6]}]
set_property PACKAGE_PIN AB15  [get_ports {ADC_PORT_ad7606_data[7]}]
set_property PACKAGE_PIN AF15	  [get_ports {ADC_PORT_ad7606_data[8]}]
set_property PACKAGE_PIN AG15	  [get_ports {ADC_PORT_ad7606_data[9]}]
set_property PACKAGE_PIN AG14  [get_ports {ADC_PORT_ad7606_data[10]}]
set_property PACKAGE_PIN AF14  [get_ports {ADC_PORT_ad7606_data[11]}]
set_property PACKAGE_PIN AD15  [get_ports {ADC_PORT_ad7606_data[12]}]
set_property PACKAGE_PIN AD16  [get_ports {ADC_PORT_ad7606_data[13]}]
set_property PACKAGE_PIN AC16  [get_ports {ADC_PORT_ad7606_data[14]}]
set_property PACKAGE_PIN AC17  [get_ports {ADC_PORT_ad7606_data[15]}]



set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_PORT_ad7606_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_PORT_ad7606_os[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_PORT_ad7606_data[*]}]

