# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/alinx/nvme4t/yang/course_s3_tcl/ax7z100/01_led_control/vivado/led_control/led_control.srcs/sources_1/bd/design_1/ip/design_1_led_control_0_0/design_1_led_control_0_0.xci
# IP: The module: 'design_1_led_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/alinx/nvme4t/yang/course_s3_tcl/ax7z100/01_led_control/vivado/led_control/led_control.gen/sources_1/bd/design_1/ip/design_1_led_control_0_0/constraints/led_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_led_control_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/alinx/nvme4t/yang/course_s3_tcl/ax7z100/01_led_control/vivado/led_control/led_control.srcs/sources_1/bd/design_1/ip/design_1_led_control_0_0/design_1_led_control_0_0.xci
# IP: The module: 'design_1_led_control_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/alinx/nvme4t/yang/course_s3_tcl/ax7z100/01_led_control/vivado/led_control/led_control.gen/sources_1/bd/design_1/ip/design_1_led_control_0_0/constraints/led_control_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_led_control_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
