set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_p]
set_property PACKAGE_PIN F9 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
############## AN871 LCD##################
set_property PACKAGE_PIN AC14 [get_ports {lcd_pwm}]
set_property PACKAGE_PIN AE12 [get_ports {lcd_hs}]
set_property PACKAGE_PIN AF12 [get_ports {lcd_vs}]
set_property PACKAGE_PIN AD13 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN AD14 [get_ports {lcd_de}]
set_property PACKAGE_PIN AG12 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN AH12	[get_ports {lcd_b[7]}]
set_property PACKAGE_PIN AE13	[get_ports {lcd_b[4]}]
set_property PACKAGE_PIN AF13 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN AH13 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN AH14 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN AJ13 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN AJ14	[get_ports {lcd_b[1]}]
set_property PACKAGE_PIN AK12 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN AK13  [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN AB14  [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN AB15 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN AF15	[get_ports {lcd_g[2]}]
set_property PACKAGE_PIN AG15 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN AG14 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN AF14 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN AD15  [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN AD16  [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN AC16 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN AC17 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN AA14 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN AA15 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN AK15 	[get_ports {lcd_r[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {lcd_pwm}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vs}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[*]}]

