set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

############## clock define##################
create_clock -period 5.000 [get_ports sys_clk_clk_p]
set_property PACKAGE_PIN F9 [get_ports sys_clk_clk_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_clk_p]

set_property PACKAGE_PIN B14 [get_ports {mdio_mdc          }]
set_property PACKAGE_PIN A14 [get_ports {mdio_mdio_io      }]
set_property PACKAGE_PIN B15 [get_ports {phy_rst_n         }]
set_property PACKAGE_PIN E13  [get_ports {rgmii_rxc         }]
set_property PACKAGE_PIN D13  [get_ports {rgmii_rx_ctl      }]
set_property PACKAGE_PIN F15  [get_ports {rgmii_rd[0]       }]
set_property PACKAGE_PIN F14  [get_ports {rgmii_rd[1]       }]
set_property PACKAGE_PIN E12  [get_ports {rgmii_rd[2]       }]
set_property PACKAGE_PIN F13  [get_ports {rgmii_rd[3]       }]
set_property PACKAGE_PIN K15  [get_ports {rgmii_txc         }]
set_property PACKAGE_PIN J15  [get_ports {rgmii_tx_ctl      }]
set_property PACKAGE_PIN G14  [get_ports {rgmii_td[0]       }]
set_property PACKAGE_PIN G15  [get_ports {rgmii_td[1]       }]
set_property PACKAGE_PIN K13  [get_ports {rgmii_td[2]       }]
set_property PACKAGE_PIN L13  [get_ports {rgmii_td[3]       }]

set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdc          }]
set_property IOSTANDARD LVCMOS18 [get_ports {mdio_mdio_io      }]
set_property IOSTANDARD LVCMOS18 [get_ports {phy_rst_n         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rxc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_rd[3]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_txc         }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_tx_ctl      }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[0]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[1]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[2]       }]
set_property IOSTANDARD LVCMOS18 [get_ports {rgmii_td[3]       }]